### ISSUE TITLE
Request: Automatic nested windows

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#102]
As per Unix based tiling window managers, it'd be  great if newly spawned windows would auto tile in a divided horizontal/vertical way rather than all horizontal.

After reading [this thread](https://github.com/lars-berger/GlazeWM/discussions/66) which details how to manually switch between horizontal and vertical modes to produce this effect. It'd be great to get some basic automation where windows spawn in a somewhat golden ratio of alternating horizontal/vertical.

**Comment by lars-berger** [comment]
The inspiration for GlazeWM comes from [i3wm](https://i3wm.org/), which behaves a bit differently than Unix WMs that automatically tile into a layout (eg. bspwm, xmonad). The downside, like you mentioned, is having to manually switch between horizontal/vertical tiling. But the upside is greater customizability when it comes to the layouts that are possible, and being able to adjust layouts on the fly. 

This behavior is quite fundamental to the WM and I don't see a clear-cut way to incorporate auto-tiling different layouts. IMO it's 2 quite different sets of WM behaviors. 

That's not to say this stuff is set in stone though. An experimental idea to speed up layouts that I've been spit-balling is to change how new windows are tiled. So currently, new windows will tile either horizontally/vertically depending on the layout of their parent container. This can sometimes be hard to keep track of though. The idea is that if the user opts in, there would instead be a global state of whether new windows are added horizontally/vertically. The layout switching keybindings (eg. `Alt+V` and `Alt+Shift+V`) would then change this global state. 

Also worth mentioning is that [Komorebi](https://github.com/LGUG2Z/komorebi) is closer to bspwm, which goes with the automatic layout approach.

**Comment by nascentt** [comment]
Many thanks for the detailed reply. That's very interesting, I had assumed the lack of auto tiling new windows was because the program was still new and you hadn't had time yet, rather than a design decision.

Ironically I learned about window tiling managers from i3 on Linux, a colleague showed me how it worked on their Linux host and it had auto tiling which is what promoted me to search for a Windows equivalent of i3 and found your project.  Maybe he did something extra to get auto tiling then.

I'll check out the other project although have been absolutely loving glazewm thus far and it'd be sad to stop using it, it'd be great if you do decide to add something. I'm not particularly fussy, I just find opening more than 4 windows on my laptop, all auto tiling horizontally, is a bit awkward to use, and trying to move some windows vertically and some horizontally in the same desktop is fiddly.

Regardless I appreciate your time and support.

**Comment by lars-berger** [comment]
Aha interesting! There's some scripts out there for i3 to accomplish this - maybe [this](https://github.com/olemartinorg/i3-alternating-layout) is what your colleague was using? 

At the moment, GlazeWM isn't scriptable. It'll be added in the future, but there's at least 2-3 major features that will likely come before it. Trying to recreate the alternating layout script will be a good test for when the scripting feature lands 👍 

Also, if you or another person coming across this issue has an idea for a concrete integration with auto-tiling layouts, feel free to reach out. I'm not opposed to the idea, but as it stands right now, I don't see a good way to implement this.
