### ISSUE TITLE
Add bar component for showing the title of the focused window

### ISSUE THREAD

**Issue by Fuann-Kinoko** [lars-berger/GlazeWM#110]
As an alternative to Window Highlight, perhaps consider adding a component  to show the name of the currently activated window?

I know the default windows taskbar does the same job, but it would be more to my liking to put it on top

Anyway, glazeWM is already a great TWM, I just wish it had more and better features!

**Comment by lars-berger** [comment]
This is a great idea 👍 Will definitely add this to the pipeline.

**Comment by lars-berger** [comment]
This has now been added to the [latest release](https://github.com/lars-berger/GlazeWM/releases)! 🎉
