### ISSUE TITLE
RMenu keybindings not triggering on German keyboards

### ISSUE THREAD

**Issue by s-v-o** [lars-berger/GlazeWM#113]
First: Great software, the first really useable tiling window manager for Window. I love it!

Because I'm using LMenu (the left ALT-Key) i.e. in Eclipse I wan't to use the RMenu (right ALT-Key) for GlazeWM shortcuts. 
But since version 1.6 this shortcut doesn't work anymore.

Exampe keybinding:

```
keybindings:
  - command: "focus left"
    bindings: ["RMenu+H", "RMenu+Left"]
```

Isn't this supported anymore or can this be corrected?

**Comment by s-v-o** [comment]
Maybe caused through PR #86?

**Comment by lars-berger** [comment]
Keybindings with `RMenu` actually seem to be behaving normally for me in 1.6.

Is an unmanaged or ignored window (ie. a window with `ignore` command in window rules) in focus when you're triggering the keybinding?

**Comment by s-v-o** [comment]
Thank you for your response.

> Keybindings with RMenu actually seem to be behaving normally for me in 1.6.

That is strange. 

I've tried it again without success:

- downloaded the [GlazeWM_x64_1.6.exe](https://github.com/lars-berger/GlazeWM/releases/download/v1.6.0/GlazeWM_x64_1.6.exe) again
- deleted temp\.net
- renamed my config, so that on start a new config is created
- LMenu (Alt) is working as expected
- RMenu isn't working (maybe expected, in the created config ALT ist used)
- replaced all occurences of "Alt+" with "RMenu+" (46 occurences)
- started again 
- keybindings aren't working
- started 1.5 again with the same config (after removing the two new configs)
- LMenu is working

After that I tried only replace `ALT+H` with `RMenu+H` without success.

> Is an unmanaged or ignored window (ie. a window with ignore command in window rules) in focus when you're triggering the keybinding?

The same windows with the same config are working in 1.5 but not in 1.6.

Further information:
- german keyboard layout
- have to start in privileged mode by using BeyondTrust
- Windows 11

What can I do to help finding the issue?

**Comment by s-v-o** [comment]
It seems to be that (at least my configuration with the handwriting support language feature) of the german keyboard layout have an effect.
I switched to english and it is working, I switched to german and it isn't working anymore.

**Comment by s-v-o** [comment]
It's really weird. I could reproduce the issue while running GlazeWM and switching with the windows taskbar icon. 
When the language is german (DEU, layout QWERTZ) the keybinding isn't working. Switching to English (US, layout QWERTY) the keybindings are working.
I have no clue what is going on here.

**Comment by lars-berger** [comment]
Keys reported as down when `RMenu` is pressed on an English keyboard:
![image](https://user-images.githubusercontent.com/34844898/189278076-6337f72b-81bd-4415-8775-4dffc1e3a7dc.png)


Keys reported as down when `RMenu` is pressed on a German keyboard:
![image](https://user-images.githubusercontent.com/34844898/189278340-18ac2062-c7ec-4374-b65f-3c0af85281b5.png)

For some reason, on a German keyboard, the left ctrl key is falsely reported as down when `RMenu` is pressed.

Will investigate a bit further, but don't really know why this would be happening and there isn't a whole lot of resources online regarding the issue. [`GetKeyState(Keys key)`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate) is the method used to check whether a key is down.

**Comment by s-v-o** [comment]
That is really strange and I wouldn't have expected that.
I haven't found any clues regarding RMenu and .NET either. 
But with your investigation you provided me with the workaround to register both `RMenu+Control` and I can confirm that this is working by only pressing the right AltGr key on german keyboard layout.

Thank you very much for all your work.

**Comment by lars-berger** [comment]
Aha, that's really clever! I'm glad there's a workaround at least - was debating reverting #86 . I'll add a section to the "known issues" section of the readme if I don't find a solution.

**Comment by s-v-o** [comment]
Yes for me the workaround is good enough :satisfied:
Thank you very much.

**Comment by lars-berger** [comment]
It turns out it's a feature ([4th bullet](https://en.m.wikipedia.org/wiki/German_keyboard_layout)). The AltGr key generates both Ctrl + Alt when pressed

[Added a section to the readme explaining the problem](https://github.com/lars-berger/GlazeWM#binding-the-right-side-alt-key-rmenu-on-certain-keyboard-layouts)
