### ISSUE TITLE
Add bar component for displaying text

### ISSUE THREAD

**Issue by presi300** [lars-berger/GlazeWM#124]
The clock can already be used as a text box but i think it'd be nice to have a separate component for that

**Comment by lars-berger** [comment]
I think that sounds like a good idea 👍 To clarify - would it be similar to the [`custom/text`](https://github.com/polybar/polybar/wiki/Module:-text) module in Polybar where it displays some hardcoded text and allows you to bind click commands?

**Comment by presi300** [comment]
Idk, i was thinking more like how qtile works (a.k.a you can type literally anything in the textbox and you can make it a click target, now that i think about it, that might be how polybar works I haven't used it too much so idk). I mean, the bar itself can already render unicode and nerd font characters just fine so yeah

**Comment by lars-berger** [comment]
This has been added in the [latest release](https://github.com/lars-berger/GlazeWM/releases)! 🎉
