### ISSUE TITLE
Window grows unexpectedly when a sub window is opened

### ISSUE THREAD

**Issue by s-v-o** [lars-berger/GlazeWM#150]
Since version 1.8 the Eclipse window grows unexpectedly when I open a sub window (like the Open Type window in Eclipse).
  
I hope these screenshots are visualizing my problem.
  
Before I open a subwindow the app is fullscreen as expected.
  
![image](https://user-images.githubusercontent.com/64085779/197136035-ff72832d-0ac1-449c-a70e-6e136b301d3b.png)
  
After opening the "Open Type" window the main window grows out of the screen. With every sub window call the main window grows further.

![image](https://user-images.githubusercontent.com/64085779/197135995-4079fbcf-12ab-47e4-91c1-0cdb7b045331.png)

But beside of this, thank you for your great work.

**Comment by lars-berger** [comment]
Trying to reproduce the issue in Eclipse version `2022-09 (4.25.0)`, but it actually seems to be behaving fine. What's the Eclipse version you're running and I'll check it out? Could still be something weird happening with the WM.

![image](https://user-images.githubusercontent.com/34844898/197375006-13a0d700-1647-4055-8fd5-0e910b19a51c.png)

**Comment by s-v-o** [comment]
Thank you for trying to reproduce the issue.
I'm using Windows 11. Maybe this could cause the issue?

Can anybody reproduce this behaviour or am I the only one?

It happens not only in Eclipse (also in my browser, but in Eclipse it was the simplest way to reproduce for me).

What can I do to deliver more data for investigation?

**Comment by s-v-o** [comment]
Actually downloaded 1.8.1 and I couldn't reproduce either. So whatever it was hopefully it's gone forever.
Thank you for your effort.
