### ISSUE TITLE
Be able to switch to previously focused workspace

### ISSUE THREAD

**Issue by gtsherman** [lars-berger/GlazeWM#151]
Just wondering if there's a way to bind a key to switch to the previously focused workspace? I didn't see this in the list of commands but wanted to make sure I'm not missing anything.

Loving GlazeWM so far. Thank you!

**Comment by azinsharaf** [comment]
this is a very necessary feature for any WM. 
 I am referencing the same feature in `Workspacer` WM. https://github.com/workspacer/workspacer/issues/337

**Comment by s-v-o** [comment]
I think this would be a very helpful feature. I find this incredibly useful on i3wm / sway (workspace back_and_forth) especially in the [auto-back-and-forth](https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth) variant: When pressing the current workspace number it switches back to the last focused one.

**Comment by kuznetsovvj** [comment]
@lars-berger Again, I did not include a new command in the default configuration - I do not know what key combination to use.

**Comment by kuznetsovvj** [comment]
feature is done
@lars-berger maybe close this issue?

**Comment by lars-berger** [comment]
This is now a part of the [latest release](https://github.com/lars-berger/GlazeWM/releases)! 🎉
