### ISSUE TITLE
priority of opacity for the entire bar versus bar component

### ISSUE THREAD

**Issue by marconetto** [lars-berger/GlazeWM#162]
Hi there,

This is my first question at this forum and I wanted to say I'm very pleased that I have found glazewm... just joined the windows world after many years of mac+linux.

I have setup in my mac that I would like to replicate in windows. Here is my mac status bar... very clean with four items:

1. ID of the workspace current + shortname of the current application
2. nickname of network
3. battery percentage (and status, charging, discharging etc..)
4. date/clock

To create this I used yabai + Übersicht
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/7735345/199343892-f94405ad-8275-48ea-9028-ebe937fbfba5.png">

I tried to create a transparent bar that would show the clock. However, if I put opacity to 0 for the entire bar and opacity to the clock component to 1, it seems the opacity of the entire bar is having priority. 

I'm wondering if there is a way to have the bar transparent and keep the clock and workspace component non-transparent.

**Comment by lars-berger** [comment]
After version [1.10.0](https://github.com/lars-berger/GlazeWM/releases), this is now possible by setting a `background` that has 0% opacity (eg. white with 0 opacity is #ffffff00)

![image](https://user-images.githubusercontent.com/34844898/208467965-349fe80d-4d74-4909-8d00-7445e4cf56ff.png)

```yaml
bar:
  background: "#ffffff00"
```
