### ISSUE TITLE
bug: Switching to a workspace on another monitor does not hide windows from the workspace that was previously focused on that monitor

### ISSUE THREAD

**Issue by jjkinsey** [lars-berger/GlazeWM#163]
Say for example that my setup includes two monitors, each of which have two workspaces bound to them. Let's call the monitors A and B. My workspaces would be laid out like this:

Monitor | Workspaces
-|-
A|1, 3
B|2, 4

What I'm observing is that if Workspace 1 is focused on Monitor A, Workspace 2 is focused on Monitor B, and globally, I have a window in Workspace 1 focused, if I switch directly to Workspace 4 (changing the workspace on Monitor B, then), the window(s) contained in Workspace 2 will not be hidden.

If in the example I instead switched from Workspace 1 to Workspace 2 (or had a window in Workspace 2 gain focus any other way, like by clicking one with my mouse), *then* to Workspace 4, the Workspace 2 window(s) would be hidden correctly.

This behavior can be difficult to notice with only one window per workspace, but if you have multiple windows per workspace (especially on the destination workspace, Workspace 4 in the example), you usually wind up with an old, should-be-hidden window covering up a window you're trying to see.

**Comment by lars-berger** [comment]
Able to reproduce this and it's pretty annoying. I'll try to get a fix out by the end of the week.

**Comment by lars-berger** [comment]
This is now a part of the [latest release](https://github.com/lars-berger/GlazeWM/releases)! 🎉
