### ISSUE TITLE
New bar component (text) is not in README.md

### ISSUE THREAD

**Issue by ColonelBucket8** [lars-berger/GlazeWM#164]
Under Bar Component Configuration section, there are only 2 components listed here. 
https://github.com/lars-berger/GlazeWM#bar-component-configuration
```
# Type of component to display. Currently only 2 component types exist:  "workspaces" and "clock".
type: <COMPONENT_TYPE>
```
Should include the new text component as it's released in [v1.8.0](https://github.com/lars-berger/GlazeWM/releases/tag/v1.8.0)

**Comment by lars-berger** [comment]
Updated by @afermar's PR 👍
