### ISSUE TITLE
Feature request: Calendar week in clock widget

### ISSUE THREAD

**Issue by s-v-o** [lars-berger/GlazeWM#196]
I often need the calendar week in my daily business.
It would be nice when I could configure the clock component so, that the calendar week is displayed.

In the [standard formatting](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) I could not find any directly working possibility.

Also the [calendar week](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear?view=net-6.0#system-globalization-calendar-getweekofyear(system-datetime-system-globalization-calendarweekrule-system-dayofweek)) can differ based on the used [CalendarWeekRule](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendarweekrule?view=net-6.0) and [FirstDayOfWeek](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.firstdayofweek?view=net-6.0).

**Comment by lars-berger** [comment]
This is now part of the [latest release](https://github.com/lars-berger/GlazeWM/releases)! Thanks for the help with this one 👌
