### ISSUE TITLE
Flow Launcher opens but it doesn't show on screen

### ISSUE THREAD

**Issue by dantearaujo1** [lars-berger/GlazeWM#248]
I use a program called Flow Launcher that i use to find files, executables and a lot of things by pressing the default keybind ALT + Space and writing words that match the file.

It seems that it works like an overlay. Unfortunately, when used with GlazeWM it opens but it does not shows up on the screen.

Is there any way to handle this?

**Comment by notblam** [comment]
I'm confused by your statement, it opens but does not show up on the screen?  What do you mean by this?  How do you know flow launcher is opening if it doesn't show up on the screen?  

The default flow config and the default GlazeWMM conflict out of the box, since both configs contain binds for alt+space.  Try using different keybinds for both FL and GWM and see if that helps.

**Comment by dantearaujo1** [comment]
![image](https://user-images.githubusercontent.com/21104508/218451143-fc0e67f2-b666-4649-9e5b-5075d9f9873f.png)

It appears when i alt tab like this image, but does not show up on screen, i'll try to change keybinds and post the results.

**Comment by notblam** [comment]
> ![image](https://user-images.githubusercontent.com/21104508/218451143-fc0e67f2-b666-4649-9e5b-5075d9f9873f.png)
> 
> It appears when i alt tab like this image, but does not show up on screen, i'll try to change keybinds and post the results.

So we recently introduced a fix to make sure flow always launches apps to the correct workspace.  This fix is not 100% perfect, and we are a bit stuck in trying to figure out a different approach.  One of the issues with this fix is when GWM is first launched, flow will is visible in this alt-tab menu, and along with that it will also not launch to the correct workspace for the very first launch.  After you launch an app, flow will disappear from the alt-tab menu and the apps should launch to the correct workspace from that point forward.  

While that explains this alt-tab menu your seeing, the issue of flow not opening up when you press the keybind is a separate issue.   The cause of that is likely what I mentioned, conflicting binds between GWM and FL.

**Comment by dantearaujo1** [comment]
Afterr changing keybinds to one that doesn't conflict, it works okay, ty for the help.
