### ISSUE TITLE
Windows PowerToys Run not showing up

### ISSUE THREAD

**Issue by Okabe9** [lars-berger/GlazeWM#249]
Hi! I've been looking for a WM similar to i3 on windows and really like the approach you're making here but I've found a major problem for me. I've been using PowerToys Run and it's really useful and makes the same work as Rofi on linux. I'd like to use both and that's why I open this issue, I'm running with the default configuration on both.

**Comment by s-v-o** [comment]
Perhaps a duplicate of #248? 

In short: Try changing the default keybindings of GlazeWM or PowerToys Run, because Alt+Space is used from both by default).
    
I'm also using PowerToys Run and it is working fine with GlazeWM (sometimes it takes a while to appear, but ok).

**Comment by Okabe9** [comment]
Yup, you're right, thanks for your answer!
