### ISSUE TITLE
reserved space?

### ISSUE THREAD

**Issue by calendulish** [lars-berger/GlazeWM#276]
I used to reserve some space on right side of my desktop to widgets, is there a way to tell glazewm to ignore that area when tiling the windows?

something like right_gap or right_margin

**Comment by lars-berger** [comment]
We could tweak `gaps.outer_gaps` to optionally accept multiple values like we do for properties like `bar.padding`,  eg.

```yaml
gaps:
  outer_gap: "20px 40px 20px 20px"
```

If you wanna take a stab at a PR, the way to go would be to change `OuterGap` in `GapsConfig.cs` to a string and then adjust the height/width/x/y of `Workspace`. `UnitsHelper.cs` can help with converting the string to ints
