### ISSUE TITLE
Microsoft Mail app doesn't get tiled

### ISSUE THREAD

**Issue by azinsharaf** [lars-berger/GlazeWM#292]
Microsoft "Mail" application (downloaded from MS Store) doesn't get tiled. I already commented out the following lines (if it matters) but it still has the issue.
Win "setting" window has the same issue. 

```
  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  # - command: "set floating"
    # match_class_name: "#32770"
 ```

**Comment by b1scu1t** [comment]
It looks like it's related to this issue: https://github.com/lars-berger/GlazeWM/issues/172

I believe this was fixed, but they haven't released it yet. You can build from source for the time being.

**Comment by azinsharaf** [comment]
i close this since don't have .net sdk on my machine and don't want to install it. I wait for the next release. Thanks.

**Comment by azinsharaf** [comment]
confirming that building form the source fixed this issue.
