### ISSUE TITLE
Crash eats all programs on other workspaces

### ISSUE THREAD

**Issue by alksndrrrr** [lars-berger/GlazeWM#293]
Glaze does not make an error log for this issue

At a certain point (after >24 hours of use time) something randomly causes the top Glaze bar to freeze and I have to ctrl+shift+esc, shut it down, and relaunch the .exe.

I absolutely love Glaze but when it does this it seems to close all the programs not on the current active workspace which is pretty frustrating, is there any setting or possible fix to just move those other workspace programs into the current one (I guess, the default windows view since there are no workspaces anymore after the crash) ? The crash doesn't bother me, just closing all my apps does... 

Thank you so much for creating this tool, it's amazing

**Comment by notblam** [comment]
This is in my opinion, our biggest issue.  

I intend to make sure this is fixed by next release.  We have one PR open that proposes a fix and we are considering an alternative approach.  

Related to #79
