### ISSUE TITLE
Feature Request: workspace_auto_back_and_forth

### ISSUE THREAD

**Issue by Petar0000** [lars-berger/GlazeWM#294]
I am not sure if this isn't already somehow possible but, this feature would be convenient https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth

Basically in the context of glazeWM it would be like 

if(focus workspace == current workspace) then focus_workspace_recent()

I think this could be achieved by adding this option to the config file and changing the following code in FocusWorkspaceHandler.cs

 if (focusedWorkspace == workspaceToFocus)
        return CommandResponse.Ok;

to

 if (focusedWorkspace == workspaceToFocus)
       workspaceToFocus = _workspaceService.MostRecentWorkspace;

or something like that.

**Comment by b1scu1t** [comment]
You can do that with:
```
 - command: "focus workspace recent"
   binding: "Alt+Y"
```

I think it is already present in the default configuration file.

**Comment by s-v-o** [comment]
It's already implemented by PR #274. 
But it is currently not released. 
Perhaps you could build it yourself from master if you really need it.

**Comment by Petar0000** [comment]
Thank you, that is what I did. Appreciate it
