### ISSUE TITLE
[Question] Shortcut for moving floating windows

### ISSUE THREAD

**Issue by rFantic** [lars-berger/GlazeWM#296]
The readme mentions this config:
`floating_window_move_amount: "5%"`
Which I assume to be setting for moving distance using Glaze, however, i could not figure out the shortcut or settings to enable this action. Is this feature supported?

**Comment by Pamesta** [comment]
This feature is not in release yet, but it uses the same keybindings as moving tiled windows (ALT+SHIFT+H, J, K, L in default config)

**Comment by rFantic** [comment]
Understood, i will close the issue then.
