### ISSUE TITLE
Weird behavior when trying to screenshot using lightshot and dual monitor setup

### ISSUE THREAD

**Issue by JulianH99** [lars-berger/GlazeWM#333]
The screens shift left when trying to screenshot using lightshot and dual monitor setup, which means half of my 1 screen appears on the left half of the first monitor, half of the second screen on the right of the first monitor as well and so on

**Comment by xslendix** [comment]
same here

**Comment by xslendix** [comment]
```
  - command: "ignore"
    match_process_name: "Lightshot"
```
solution ^

**Comment by JulianH99** [comment]
Gonna try that, thanks!
