### ISSUE TITLE
focus_border_color does not seem to work...

### ISSUE THREAD

**Issue by rwijtvliet** [lars-berger/GlazeWM#334]
As per the readme:
```
(...)
general:
  # Whether to show floating windows as always on top.
  show_floating_on_top: false
  focus_border_color: "#42c0fb"
(...)
```
...but no border is shown on the focused window.

Is there a thickness that must be set?

**Comment by rwijtvliet** [comment]
Ah, I see it's already been fixed upstream. I'll just wait for the release :)

**Comment by rwijtvliet** [comment]
Ah, no, actually, that PR is for windows 11. It's not working for me on W10 enterprise.

**Comment by notblam** [comment]
> Ah, no, actually, that PR is for windows 11. It's not working for me on W10 enterprise 22H2.

The API for Windows 10 will likely never support this natively.  Other approaches have been done before that involve a second window that is created and placed behind the floating window.  We decided that it was a little too hacky and out of scope for this project.  

On another note, the W11 API has it's own issues, like you can't set the border width, borders are always 1px.  I'm hoping Microsoft improve this API going forward with W11, but I don't think they will update this on W10.
