### ISSUE TITLE
Some feature suggestions.

### ISSUE THREAD

**Issue by ParasiteDelta** [lars-berger/GlazeWM#34]
Just want to start off by saying that this is great. I've always wanted tiling on Windows to make it slightly less annoying to deal with, and this actually delivers. That being said, there are some points that need improvement.

Firstly, I'm not sure if it's just Firefox being Firefox, but the browser window in my case does not appear to respect the gap rules. Not sure why, but it's roughly twice the gap size as what is set (10, at the time of writing).

Next, there needs to be a hot reload for the config file, or at least a manual reload that can be triggered via keybind. I made a script to just restart it on change, but it's a pretty hacky solution.

Finally, the rules for fullscreen applications needs work. If you try to run a game from a launcher, for example, it currently treats the launcher as the parent window before either hiding or crunching the window, requiring you to manually move the window over and resize it in-game. More to the point, it would be incredible if we could set rules in the config for fullscreen or specific applications, with options such as floating or grid, position, etc.

Again, thank you for your work and for making Windows less of a pain to deal with.

**Comment by lars-berger** [comment]
Thanks for all the feedback, it's much appreciated 👍 

The first point seems to be related to [this issue](https://github.com/lars-berger/GlazeWM/issues/33). Will try to address this ASAP.

Definitely agree about adding some way of reloading the config. Used the same feature in i3 plenty of times, so I understand the need for it.

Regarding the third point - currently there's no special handling of fullscreen windows. If a window is non-resizable (ie. there are no sizing borders on the edges of the window), then it's initialized as a floating window. A floating window will retain its original width/height and the WM tries to center it in the workspace. This means that most games are initialized as floating windows, which works fine in most cases. Having a bit of trouble following along with your specific case though, could you give a bit more details, or even a screen recording?
