### ISSUE TITLE
Bug: Glaze WM wont let PowerToysRun execute

### ISSUE THREAD

**Issue by Yzuhou** [lars-berger/GlazeWM#346]
I tried diferent combinations of hotkeys in order to test if it was the windows key the one causing the bug but it didnt worked. 
I tested: 
- windows + space
- alt + space
- right alt + space
- ctrl + space
- right alt + p

**Comment by lars-berger** [comment]
GlazeWM has a keybinding registered for alt+space, which doesn't get forwarded to other apps. You could either unmap that keybinding in the GlazeWM config, or change powertoys to use a different keybinding
