### ISSUE TITLE
Keybindings with Alt also trigger when using AltGR

### ISSUE THREAD

**Issue by Cyklan** [lars-berger/GlazeWM#35]
I have the following keybinding:
```yaml
- command: "focus workspace 1"
  binding: "Alt+1"
```

It also triggers when I press AltGr+1

This happens with every keybinding that uses the Alt key

**Why is this bad?**
On the german keyboard layout, AltGr is used for lots of characters, including but not limited to:
- AltGr + 2: ²
- AltGr + 3: ³
- AltGr + 7: {
- AltGr + 8: [

Just using alt (e.g. Alt + 2) would not produce the specific character (in this case ²)

**Comment by lars-berger** [comment]
If it's the left alt key that you'd like for keybindings, could you see if it works as expected with `LMenu` instead (eg. `LMenu+1`)? The available keys can be found [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-5.0#fields).

**Comment by Cyklan** [comment]
That worked! I didn't even think of it - my workaround was recompiling the source code with the LMenu || RMenu check removed 😅. Just using LMenu is so much easier. Thanks so much :)
