### ISSUE TITLE
[question] Logo key as super 

### ISSUE THREAD

**Issue by jadedFella** [lars-berger/GlazeWM#356]
Is it possible to bind the logo key (the windows key on most laptops) as the super key?
I come from an i3 background and I have a habit of using mod4 (Win) as my super instead of mod1 (Alt). If it is possible please mention the name of the key to write in config (Win didn't work and glaze gave errors).
Sorry if it's a dumb question.

**Comment by lars-berger** [comment]
The problem with keybindings on the Win/super key is that it's not possible (or a big hassle) to override some of the default OS keybindings. For example, to unmap `LWin+L` you have to disable logout functionality...

If you still want to go down that route, `LWin` is the key name to use in GlazeWM config

**Comment by jadedFella** [comment]
thanks!

**Comment by Archie-2021** [comment]
> The problem with keybindings on the Win/super key is that it's not possible (or a big hassle) to override some of the default OS keybindings. For example, to unmap `LWin+L` you have to disable logout functionality...
> 
> If you still want to go down that route, `LWin` is the key name to use in GlazeWM config

IIRC, When using PowerToys it overrides keys without a problem. But AHK can't do the same. I would love to have my Alt key back if possible
