### ISSUE TITLE
PowerToys Run not rendering when WM is active

### ISSUE THREAD

**Issue by raf2k07** [lars-berger/GlazeWM#36]
The PowerToys Run combo box does not show up when the WM is running. (Windows 11)

**Comment by lars-berger** [comment]
There might be a conflict of keybindings. Is PowerToys Run triggered with `Alt+Space`? In the default config, this is bound to toggle focus mode (to switch focus between tiling and floating windows).

**Comment by raf2k07** [comment]
This seems to be the issue. Thanks!
