### ISSUE TITLE
How do I setup the BSP like tiling as shown in the demo GIF?

### ISSUE THREAD

**Issue by st0le** [lars-berger/GlazeWM#37]
How do I setup the BSP like tiling as shown in the demo GIF?

After the initial 3 terminals are added as new column. The GIF shows 2 Columns, and new terminals added as rows only in the second column. The GIF further shows BSP like layout.

Is this supported yet?

![image](https://user-images.githubusercontent.com/3803209/163663275-95c1eccc-a414-4bb6-9ff9-bdf27aeca08f.png)

![image](https://user-images.githubusercontent.com/3803209/163663289-d0a6b978-7052-4238-b9ed-e503da6e5e15.png)

**Comment by lars-berger** [comment]
Windows will tile horizontally as they open, but that can be changed by switching the layout to vertical (`Alt+V` by default). 

To achieve the layout in the first screenshot: open 2 windows and set focus to the window on the right-side. Then, set the layout to vertical, and when opening the third window, it'll tile vertically.

To get the layout in the 2nd screenshot, change the layout of the 3rd window to horizontal (`Alt+Shift+V` by default), and the next window will tile horizontally.

Ref [default keybindings](https://github.com/lars-berger/GlazeWM#default-keybindings)

**Comment by FireBanana** [comment]
It would be nice if this was automated, or the default layout
