### ISSUE TITLE
How to turn off the upper black bar _

### ISSUE THREAD

**Issue by abdullah-can** [lars-berger/GlazeWM#45]
Its kinda blocking the desktop icons

**Comment by lars-berger** [comment]
There isn't an explicit option to disable the bar at the moment, but it'll be hidden if you set the height and opacity of the bar to 0 in the user config (at `C:\Users<YOUR_USER>\.glaze-wm\config.yaml`) :

```yaml
bar:
  height: 0
  opacity: 0
```
