### ISSUE TITLE
Question: How to move workspace to Monitor and focus monitor?

### ISSUE THREAD

**Issue by 8** [lars-berger/GlazeWM#48]
Hi,

first I wanted to thank you for the great application!

I've used Xmonad on linux and Workspacer on Windows (which takes the layouting approach of Xmonad) in the past and I think GlazeWM takes inspiration vom i3, which I tried out only for a short period of time, so I may be oblivious to an obvious solution to my following questions:

1. How do I move a workspace from one monitor to the next?

eg. using Xmonad/workspacer if I am focused on monitor 1 and I press ALT-2 to switch to workspace 2, workspace 2 is used on monitor 1. If it was visible on monitor 2, the workspace that was previously being shown on monitor 1 is switched with monitor.

I have searched for an i3-based solution and found:
https://faq.i3wm.org/question/4609/how-to-move-workspace-to-monitor.1.html
which mentions the use of `move workspace to output right` and `move container to output right` as possible solutions.

2. How do I move focus from one monitor to the another?

eg. using Xmonad/workspacer provides alt-wer

I've searched for an i3-based solution and found:
https://faq.i3wm.org/question/4335/move-focus-to-monitor.1.html
which mentions the use of `focus output right` as a possible solution.

I've quickly glanced at the source code, but I don't think those commands are implemented atm - is this correct? If not, is this on the roadmap or are there any other solutions that I am not aware of?

Thank you!

Take care,
Martin

**Comment by 8** [comment]
> 1. How do I move a workspace from one monitor to the next?

Will be enabled using the command `move workspace to output <DIRECTION>`, which is tracked by the issue #50.

**Comment by lars-berger** [comment]
Hey, I appreciate the feedback. Cool to see people with different WM choices trying this out.

Regarding 2., there's of course the directional focus commands (eg. `Alt+H`) and workspace focus commands (eg. `Alt+1`), but if those don't fit your needs, I could make another issue for this.

Also note that the command string `move workspace to output <DIRECTION>` might change further down the line. There's some differences in architecture and naming compared to i3.

**Comment by lars-berger** [comment]
Being able to move workspaces in now possible in the [latest release](https://github.com/lars-berger/GlazeWM/releases) via `move workspace <DIRECTION>`

If you still feel like the currently available commands don't solve your use cases, feel free to open a new issue for the `focus output right` suggestion 👍
