### ISSUE TITLE
Be able to move workspaces between monitors

### ISSUE THREAD

**Issue by lars-berger** [lars-berger/GlazeWM#50]
Be able to move entire workspaces directionally to different monitors. Similar to i3wm's command `move workspace to output <DIRECTION>`.

**Comment by itschip** [comment]
And perhaps, a configuration to only allow one monitor to hold all workspaces, so you can keep your other monitors in a "default state"?

**Comment by lars-berger** [comment]
This is now a part of the [latest release](https://github.com/lars-berger/GlazeWM/releases) thanks to @kuznetsovvj 🎉

**Comment by Qwerty-Space** [comment]
Hi, this doesn't appear to be documented in the readme
