### ISSUE TITLE
Keybinds + your config - impossible to make vert/horizontal

### ISSUE THREAD

**Issue by scubamount** [lars-berger/GlazeWM#51]
The current default keybinds work, will continue testing program. Downside is I cannot for the life of me figure out how to get something to tile horizontally and vertically at the same time besides opening a new window utilizing start menu and using the horizontal or vertical layout selector. I rarely need to open new windows by hitting start menu, open a new program, and selecting where it should go... I commonly need to reconfigure where my windows are already.

If this is my lack of knowledge and I have not been concise, I will resolve issue immediately

Edit: It's frustrating to open a window and then need to move it across a workspace and then it removes the horizontal or vert tiling without being able to have vert and horiz at the same time. Having a 1x2 or a 2x2 is super important to me. Whereas having a 1x1x1 is not... Accidentally moving a tile the wrong way messes up everything and windows must be closed and opened to orient correctly.

Example:
Alt+Shift+V > Alt+Shift+Left = goodbye horizontal/vertical tiling.
Alt+V + > Alt+Shift+left = goodbye horizontal/vertical tiling

**Comment by scubamount** [comment]
Example: 
Alt+Shift+V  > Alt+Shift+Left  = goodbye horizontal/vertical tiling.
Alt+V + > Alt+Shift+left = goodbye horizontal/vertical tiling

**Comment by ianelletson** [comment]
I'm running into this same issue; I'm unsure how to get the same behavior as displayed in the example in the README

**Comment by lars-berger** [comment]
> Accidentally moving a tile the wrong way messes up everything and windows must be closed and opened to orient correctly.

I'm having trouble following along with your specific example. AFAIK there shouldn't be a case where you'd have close and re-open windows just to get a certain layout back. Could you send a screenshot or a quick diagram in Paint of your desired layout, as well as the move that messes things up?

@ianelletson To get the tiling behavior shown in the demo GIF, see [here ](https://github.com/lars-berger/GlazeWM/issues/37)

**Comment by scubamount** [comment]
@lars-berger Hey lars, apologies for not being concise. What I meant about this was that we would like to tile windows that have already been opened. So If we have 4 windows open vertically, how would I rearrange them so that instead of 1x4, they would be open 2x2, without opening a new window?

**Comment by lars-berger** [comment]
[Think this should solve your use case](https://streamable.com/sjoyn0). Let me know whether this can be closed 👍

**Comment by scubamount** [comment]
oh my gosh. Yes. I messed around for hours but somehow couldn't figure this out. Thank you. This is it.
