### ISSUE TITLE
Ultra wide causes explorer crash

### ISSUE THREAD

**Issue by scubamount** [lars-berger/GlazeWM#52]
![image](https://user-images.githubusercontent.com/59990200/163850689-321764f2-3a3b-44e4-a9bb-01ab531ccc7e.jpeg)

After launching, this line pops up. Only thing that would fix it reboot even after restarting explorer and exiting program etc..  was able to visually capture with snippet tool this line. 

This has only applied on ultra wide monitor with 1 workspace.

Edit: - right clicking desktop would have infinite spinning circle after this

**Comment by lars-berger** [comment]
Could you send a screen recording of what happens when launching? It's difficult to diagnose such an issue with only an image.

The only GUI that the WM renders is the horizontal bar at the top of the screen, but this doesn't look like it could be the bar.

**Comment by scubamount** [comment]
Was not able to replicate another time
