### ISSUE TITLE
Issues with multiple monitors: cant pick which screens to tile on

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#55]
Been using the app for a few days on my laptop, and it's been a good experience.
I tried it today on a pc with multiple screens and found it kept tiling my windows on the 3rd screen and ignoring the other 2.  I tried to drag or move with the alt keyboard shortcuts but anytime I'd open a new window, all the other windows would be moved over to the third screen again.

Would be great to get multiple monitor support, or at the least the ability to pick which screens to tile on and which to ignore,  (and if only one screen can be supported let the user pick which screen to use for tiling).

Many thanks for the great app.

**Comment by lars-berger** [comment]
When a new window is opened, it'll be added as a sibling to whichever window currently has focus. Could you double check whether behavior is working as expected or whether this is some sort of bug with 3 monitors? Personally running a multiple monitor setup as well, but with dual monitors.

**Comment by nascentt** [comment]
In my brief tests, the monitor I was foused on (my Windows 'primary ' and middle-most screen) was being ignored and my third screen (which I usually keep as a passive dashboard/output ended up becoming the primary monitor glazewm used.  I did unplug and turn off the 3rd screen and open new windows and clicked around on the other screens to try to show it it was my focused screen, but it ddn't seem to help.  I didn't experiment with 2 screens much though, so can try again tomorrow.   Happy to run any alpha/debug versions of the app to output additional info/logging if it'd help.
I'll try once more with 2 screens tomorrow to double-check and report back.

**Comment by nascentt** [comment]
Ok reading your edit it seems that I misunderstood about being able to drag windows around. I thought you rescanned the open windows anytime one changes and tiled with that new info.  I didn't realise that dragged windows are just ignored as it were and the next time glaze scans through them it puts it back when it remembers it being.
Because I was using just one screen before I knew dragging my mouse caused some issues but because it's always reticle to that same screen I just assumed the app was handling it.

So yeah multiple monitors works. You just have to use only keyboard.

It would be nice to get some mouse drag support if there's anyway to do it.

To be honest I've been trying to avoid using the keyboard so it definitely explains the issue if it's dependent on the keyboard navigation.

So yeah if I move a window to the screen of my choice with alt+shift+arrow then all subsequent windows do tile to that same screen.  So I guess that's how a screen is focused.
I'll close the ticket.
