### ISSUE TITLE
Typing in notepad plus plus causes window movement

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#57]
Rather minor one but still consistent and reproducible.
Typing in notepad++ causes the application window to start resizing by itself.

Steps to reproduce, just type in notepad++
Example word "typing"

The notepad++ window seems to keep moving and resizing by itself with each keypress then going back to its original state again.

**Comment by lars-berger** [comment]
Someone else also mentioned they were having trouble with notepad++, but I'm struggling to [reproduce the issue](https://streamable.com/s4ukmi).

Using version `v8.3.3 (64-bit)` (info available in the notepad++ menu bar via `?` -> `Debug Information`)

**Comment by nascentt** [comment]
It's definitely a weird one as it seemed to occur randomly whilst I was typing sentences. At first o thought it was certain letters, but I believe it's combinations of successive letters.
The reproducible word I gave above was "typing"

If I type  "typing on multiple lines it happens each time.

**Comment by nascentt** [comment]
Many thanks, that rule indeed solves the issue!

Does that mean anyone using notepad++ will have to find this thread and add it themselves or will it become a default rule in the future?

This issue can be closed.

**Comment by lars-berger** [comment]
Will get this added as a default rule in the next release.

**Comment by lars-berger** [comment]
This has been addressed now in the [latest release](https://github.com/lars-berger/GlazeWM/releases) 👍

Noticed that [workspacer](https://github.com/workspacer/workspacer) had a good system for dealing with such windows, so took some inspiration from them.
