### ISSUE TITLE
Prevent keybindings from firing when an ignored app is focused

### ISSUE THREAD

**Issue by HiMyNameIsIlNano** [lars-berger/GlazeWM#64]
Hi @lars-berger,

first of all thanks you very much for the awesome work you have done with GlazeWM. Keep up the good work.

I have a question on how the 'ignore' functionality works. I would like to exclude Intellij Idea from being managed by GlazeWM as I am using a lot of shortcuts in my IDE that overlap with the WM (e.g. Alt+1 for example is moving to the project tab in Idea but it is also focusing workspace 1). I tried using ignore and I seem to miss a bit how it is supposed to work (or maybe I am simply using it wrong). In my config file I have:

```
window_rules:
  - command: "ignore"
    match_process_name: "/idea64/"
    match_class_name: "SunAwtFrame"
```

and the result I get is that the window is persisted on all the workspaces (which sounds reasonable to me as it is ignored) but I am not sure whether my understaning is correct or not and also pressing `Alt+1` seems to still trigger the WM as the IDE does not set the focus on the Project tab.

Am I doing something wrong here? Could you please help me in getting this right?

Cheers and thanks again.

**Comment by lars-berger** [comment]
You're using the command correctly - it's an oversight on my part. Currently, when a window is ignored, it means the WM won't try to move it around and that focus can't be set to it via focus commands (eg. "focus left").

It would definitely be more intuitive for WM keybindings to not fire while the ignored app is in focus though. Will take a look into how difficult this would be to implement and hopefully it can be squeezed into the next release.

**Comment by HiMyNameIsIlNano** [comment]
Sweet, thanks for the quick reply. I would be really glad to test it once it is released.

**Comment by lars-berger** [comment]
This has been added now to the [latest release](https://github.com/lars-berger/GlazeWM/releases)
