### ISSUE TITLE
Borders of Electron apps are resized inconsistently

### ISSUE THREAD

**Issue by ParasiteDelta** [lars-berger/GlazeWM#73]
_Pseudo-apps: applications that utilize Chromium/Headless Chromium alongside packages like Electron to cobble together a dedicated desktop application with HTML/CSS or a web-app; a dedicated Chromium install for a web-app with extended system permissions and capabilities._

When using LibreWolf and similar or Streamlink Twitch GUI (both left), the sizing and positioning is now correct and consistent as of 1.4. However, now Discord and Spotify (both right) are no longer sized correctly. Discord has some slight overlap on the left or right edges, while Spotify has significant overlap on the right and bottom edges, to the point of requiring at least 12 for the inner and outer gaps to compensate for the overlap (Pic 1). I have tried moving workspaces, moving the windows, toggling floating, restarting GWM and the rig itself, and have updated from 1.4 to 1.4.1; no change.

**Pic 1: inner and outer gaps set to 12**
![image](https://user-images.githubusercontent.com/19669733/167467076-1a9ff35e-5a45-425d-96f5-9480e5ef9f0f.png)

**Pic 2: inner set to 5, outer set to 10 (what I was using before)**
![image](https://user-images.githubusercontent.com/19669733/167468295-c56a2de0-22af-48f5-87a4-9d9be27ef82a.png)

**Comment by lars-berger** [comment]
Think I've spotted the problem. Put out a [new release](https://github.com/lars-berger/GlazeWM/releases) - could you check whether it fixes your issue?

**Comment by ParasiteDelta** [comment]
Wow, that was a quick patch. Can confirm that it works, but I think C# applications with a custom frame might be a new issue. However, it's nowhere near as severe, so it can wait for your next update :) Thank you for your work.

**Result, 15 inner and outer gaps:**
![image](https://user-images.githubusercontent.com/19669733/167622665-819a7b02-6202-4fc6-b464-b63196038e67.png)

**Comment by ParasiteDelta** [comment]
My apologies, but it appears that now other things are breaking. Programs that use a custom frame now appear to be at roughly half the gap that they should be, but only on the sides and the bottom; the top appears to be managed correctly, oddly enough.

_**Inner/Outer Gaps set to 15:**_

**Pic 1, left to right: Affinity Designer, Playnite, Discord, Spotify**
![image](https://user-images.githubusercontent.com/19669733/167627144-08a2429b-4863-4818-851e-e57e00223063.png)

**Pic 2, left to right: Adobe Photoshop, Playnite, Discord, Spotify**
![image](https://user-images.githubusercontent.com/19669733/167627309-fbf860f0-7c0f-4ed9-9210-0c02c62b5e2f.png)

**Pic 3, left to right: Adobe Photoshop, Affinity Designer, Playnite, Discord, Spotify**
![image](https://user-images.githubusercontent.com/19669733/167627427-7371f60f-0252-422d-abc2-9b4235d6881f.png)
