### ISSUE TITLE
RFI: Run external commands

### ISSUE THREAD

**Issue by HiMyNameIsIlNano** [lars-berger/GlazeWM#76]
Hi @lars-berger,

I was taking a look at the animated gif you posted in the README section of the project and from what I gather it seems possible to launch external commands directly within GlazeWM (e.g: Terminal Emulator, Text Editor, etc). At the moment I am using AHK to do that but I was just wondering if that is necessary.

Thanks in advance.

**Comment by lars-berger** [comment]
Was running an AHK script to open terminal windows in the readme GIF. Think it could still be a good feature to be able to execute shell commands via keybindings, similar to the `exec` command in i3.

I'd imagine it's a bit trickier to implement on Windows though. There doesn't seem to be a good way to get the user's preferred shell (eg. Bash, CMD, Powershell) and the way commands are passed to these shells may be different. One solution is to just always use CMD as the shell and provide some examples of how to launch other shell commands from CMD, eg. `powershell 'echo test'` and `bash -c 'echo test'`.

**Comment by HiMyNameIsIlNano** [comment]
Hi @lars-berger,

thanks for taking the time to reply. I did mean to suggest any change or feature to the project. I think the amount of features in GlazeWM is more than enough IMHO. 

The only thing I really miss is being able to remap the Window Key as that would enable a lot more keystrokes that do not overlap with GlazeWM and thus the need to add exclusions, but this is not a glazewm issue, rather a windows one. I would have probably leveraged more AutoHotKey and externalize the Keybinding to call programs in AHK and maybe use a socket to let AHK and GlazeWM to communicate. 

Something along the lines:

`
// Autohotkey
#+K:
if (glazewm is running) {
  send 'resize window' to 'glazeWM'
  end
}
send #+K
`

This way glazewm would only act as a window manager, but then again I am just a humble user. Please don't take this as a critic because it is not. The effort you are taking into making this project even more and more polished are to be respected and I want to thank you again for making windows a bit more usable for me!

Thanks in advance
