### ISSUE TITLE
Key bindings bug when more keys pressed than binding

### ISSUE THREAD

**Issue by KiLLeRRaT** [lars-berger/GlazeWM#85]
I found a problem with the key bindings.

I bound focus workspace 1..9 to `Alt+1` .. `Alt+9`.  This works, but when I press `Control+Alt+1` the program checks to see if `Alt` is pressed, and if `1` is pressed, and then runs the focus workspace 1... It should ignore that, since I bound another application to `Control+Alt+1`.

So we need to check all the currently pressed modifiers and keys, and compare exact match with the key bindings. If it doesn't match EXACTLY, then ignore it.

I had a very quick look but I couldn't quite figure out how it works.

It's somewhere below:

I think this needs to be somehow flipped, or change to do an exact compare:
https://github.com/lars-berger/GlazeWM/blob/622a7f9b46842d1f1c8a0396e73429aea341dea4/GlazeWM.Infrastructure/WindowsApi/KeybindingService.cs#L103

https://github.com/lars-berger/GlazeWM/blob/622a7f9b46842d1f1c8a0396e73429aea341dea4/GlazeWM.Infrastructure/WindowsApi/KeybindingService.cs#L133

Cheers,

**Comment by KiLLeRRaT** [comment]
I have no created this PR that solves the issue for me

https://github.com/lars-berger/GlazeWM/pull/86.

**Comment by lars-berger** [comment]
This has been added to the [latest 1.6 release](https://github.com/lars-berger/GlazeWM/releases)! 👍

**Comment by KiLLeRRaT** [comment]
Awesome, thanks @lars-berger!
