### ISSUE TITLE
Reload user config without restart

### ISSUE THREAD

**Issue by ParasiteDelta** [lars-berger/GlazeWM#90]
Started using 1.5 today, and it seems to work a treat, with the issue in thread #80 appearing to have been solved for the time being. 

Anyways, would it be possible to incorporate a kind of hot-reload for the config file, something that could be triggered on keybind or in the tray menu? The lack of attribute docs on what can be specified is an issue in and of itself, but needing to close and reopen the WM to see the changes from a single line is a bit much, especially since it discards your layout with no way to preserve it outside of explicit rulesets. That's also a pain, since I can't find anything for assigning workspaces to X or Y panel, so setting program workspace requirements is a half-measure.

**Comment by lars-berger** [comment]
Totally agree - think I'll work on implementing hot reloading after the feature that's currently in the pipeline 👍 

Could you explain "assigning workspaces to X or Y panel"? Do you mean assigning a workspace to a specific monitor/screen?

**Comment by ParasiteDelta** [comment]
Exactly, sorry. I noticed that you can assign programs to certain workspaces, but I can't find anything about assigning workspaces to specific panels, so in the example above it would be a half-measure to assign certain programs to certain workspaces since you cannot dictate which panel those workspaces go to, so you can't exactly save your current layout if the program closes or crashes. Is there a way to detect which panel is set as your primary display and which is set as your secondary/tertiary/etc. in the Windows API? If so, even that would be a great help, as the goal would be to set all odd numbered workspaces to display on the primary panel, with all even numbered workspaces moving to the secondary panel.

**Comment by lars-berger** [comment]
This has been added in the [latest 1.7 release](https://github.com/lars-berger/GlazeWM/releases) :tada: 

The new command is `reload config`. [Example keybinding](https://github.com/lars-berger/GlazeWM/blob/9301fcc919c14dab885a7c6c60bb4a3bcf46d508/GlazeWM.Bootstrapper/sample-config.yaml#L109)
