### ISSUE TITLE
Minimize window command

### ISSUE THREAD

**Issue by crimist** [lars-berger/GlazeWM#93]
Would help productivity, something similar to WinKey+DownArrow but without opening the Windows menu.

Example:

```
- command: "minimize"
   binding: "Alt+M" 
```

**Comment by lars-berger** [comment]
Sure, I'll see if I can get this added to the upcoming release 👍

**Comment by lars-berger** [comment]
This has been added to the [latest 1.6 release](https://github.com/lars-berger/GlazeWM/releases)! 👍
