### ISSUE TITLE
Can I set all my workspaces to one monitor?

### ISSUE THREAD

**Issue by itschip** [lars-berger/GlazeWM#94]
I have three monitors, but I'd like only one to hold all my workspaces, is it possible at the current time?

**Comment by lars-berger** [comment]
I'm not 100% sure what you mean.

What would be the expected behavior of the WM on the other monitors?

**Comment by itschip** [comment]
Expected behavior on the other monitors would be to move windows freely, both position and size.

**Comment by lars-berger** [comment]
Window events like close, minimize, etc. are global and it would add a lot of complexity having to handle essentially 2 sets of behaviors for each event: one set where the window is on the monitor where the WM is active and another set on the other monitors. Eg. for handling window minimize - you'd probably want the window to tile on restore on the WM monitor and restore to its original position on the other monitors.

Is there a particular gripe you've encountered with the WM that this would solve? You can get pretty close to the behavior you describe by just using floating windows (toggle floating via `Alt+Shift+Space`) on the other monitors.

**Comment by itschip** [comment]
This works. Thanks.
