### ISSUE TITLE
Command keybinding doesn't accept semicolon

### ISSUE THREAD

**Issue by simpchristy** [lars-berger/GlazeWM#97]
Hi there, I'm trying to set a command's keybinding to "Alt+;" but the error log says `Requested value ';' was not found.` I've attached the whole error log, I wonder if you can tell me if/how this is possible. Thanks.

[errors.log](https://github.com/lars-berger/GlazeWM/files/9288508/errors.log)

**Comment by lars-berger** [comment]
You can create bindings using the semicolon key via the below:

```
keybindings:
  - command: "focus left"
    binding: "Alt+OemSemicolon"
```

A full list of keys that can be used for keybindings can be found [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-5.0#fields)

**Comment by zkxjzmswkwl** [comment]
In case anyone stumbles across this from search engine results, recent-ish updates have allowed for the use of `;`. Notably, use of `OemSemicolon` won't result in desired functionality nor will it result in errors.
